In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df = pd.read_csv("./CSVs/churn_modeling.csv")
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x = df.iloc[:,3:-1]
x.head(5)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [4]:
y = df.iloc[:,-1]
y.head(5)

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
geography = pd.get_dummies(x['Geography'])
gender = pd.get_dummies(x['Gender'])
x = pd.concat([x,geography,gender],axis=1)
x.head(5)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  France  Germany  Spain  Female  \
0          1               1        101348.88       1        0      0       1   
1          0               1        112542.58       0        0      1       1   
2          1               0        113931.57       1        0      0       1   
3          0               0         93826.63       1        0      0       1   
4          1               1         79084.10       0        0      1       1   

   Male  
0     0  
1     0  
2     0  
3     0  
4     0

In [10]:
x = x.drop(['Geography','Gender'],axis=1)
x.head(5)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  France  Germany  Spain  Female  Male  
0               1        101348.88       1        0      0       1     0  
1               1        112542.58       0        0      1       1     0  
2               0        113931.57       1        0      0       1     0  
3               0         93826.63       1        0      0       1     0  
4               1         79084.10       0        0      1       1     0

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
x_train

array([[ 1.78974378,  0.94394225,  1.04271518, ..., -0.57388614,
        -0.91255717,  0.91255717],
       [ 0.26040483,  2.35932486, -0.35053238, ...,  1.74250594,
         1.09582175, -1.09582175],
       [-0.22526362, -0.47144036,  0.3460914 , ...,  1.74250594,
        -0.91255717,  0.91255717],
       ...,
       [-1.97160337,  0.09471269,  0.3460914 , ..., -0.57388614,
         1.09582175, -1.09582175],
       [ 0.60140608, -0.47144036, -1.04715616, ..., -0.57388614,
         1.09582175, -1.09582175],
       [ 0.21907135,  0.09471269,  1.73933896, ..., -0.57388614,
        -0.91255717,  0.91255717]])

In [15]:
import keras

In [22]:
from tensorflow.keras import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [24]:
classifier = keras.Sequential()

In [30]:
classifier.add(keras.layers.Dense(6,activation='relu',kernel_initializer='he_uniform',input_shape=(13,)))

In [31]:
classifier.add(keras.layers.Dense(6,activation='relu',kernel_initializer='he_uniform'))

In [34]:
classifier.add(keras.layers.Dense(1,activation='sigmoid',kernel_initializer='glorot_uniform'))

In [35]:
classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [37]:
model_history = classifier.fit(x_train,y_train,validation_split=0.33,validation_batch_size=10,epochs=100)

Epoch 1/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8587 - val_loss: 0.3647 - val_accuracy: 0.8535
Epoch 2/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8559 - val_loss: 0.3609 - val_accuracy: 0.8550
Epoch 3/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8593 - val_loss: 0.3635 - val_accuracy: 0.8497
Epoch 4/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8565 - val_loss: 0.3691 - val_accuracy: 0.8425
Epoch 5/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8559 - val_loss: 0.3612 - val_accuracy: 0.8569
Epoch 6/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8567 - val_loss: 0.3612 - val_accuracy: 0.8550
Epoch 7/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3470 - accuracy: 0.8614 - val_loss: 0.3799 - val_accuracy: 0.8326

Epoch 58/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8589 - val_loss: 0.3631 - val_accuracy: 0.8485
Epoch 59/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3400 - accuracy: 0.8612 - val_loss: 0.3586 - val_accuracy: 0.8512
Epoch 60/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8606 - val_loss: 0.3616 - val_accuracy: 0.8504
Epoch 61/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3389 - accuracy: 0.8599 - val_loss: 0.3587 - val_accuracy: 0.8512
Epoch 62/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3404 - accuracy: 0.8595 - val_loss: 0.3597 - val_accuracy: 0.8519
Epoch 63/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3386 - accuracy: 0.8595 - val_loss: 0.3570 - val_accuracy: 0.8531
Epoch 64/100
168/168 [==============================] - 0s 2ms/step - loss: 0.3385 - accuracy: 0.8595 - val_loss: 0.3572 - val_accuracy:

In [38]:
y_pred = classifier.predict(x_test)

63/63 [==============================] - 0s 581us/step


In [41]:
for i in range(len(y_pred)):
    if(y_pred[i] >= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
y_pred

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [42]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
cm

array([[1475,  224],
       [ 103,  198]], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_pred,y_test)
accuracy

0.8365