In [1]:
import numpy as np

In [3]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [5]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
unit_price = np.array([[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
np.dot(unit_price,units)

array([[34400, 50000, 64400]])

In [11]:
cost_in_dollars = np.array([[200,2020,250],[68,79,105],[110,140,180],[80,85,90]])

array([[ 200, 2020,  250],
       [  68,   79,  105],
       [ 110,  140,  180],
       [  80,   85,   90]])

In [12]:
cost_in_ruppes = cost_in_dollars*75
cost_in_ruppes

array([[ 15000, 151500,  18750],
       [  5100,   5925,   7875],
       [  8250,  10500,  13500],
       [  6000,   6375,   6750]])